version: '3.8'

services:
  telegram-java:
    image: telegram-app-1
    build: .
    ports:
      - "8084:80" # Mapea el puerto 8081 del host al 8080 del contenedor
    networks:
      - red-external-network
    restart: always

networks:
  red-external-network:
    external: true
